### ISSUE TITLE
Catch SSL/Socket Timeout

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok-client#139]
This error has been happening more frequently (and sometimes I can replicate it, but not consistently) - I'm not quite sure what the cause is (it could be app engine related) but if we can't diagnose it we should at least catch the error and print out a friendly message. 

![image](https://cloud.githubusercontent.com/assets/882381/11525384/89d7b9ce-9887-11e5-91f6-20841ef1e4b6.png)

**Comment by knrafto** [comment]
```
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case

Submit... 100% completee
Backup successful for user: knrafto@berkeley.edu
URL: https://ok-server.appspot.com/#/5631829415559168/submission/6227599011348480

Checking for software updates...
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ok/__main__.py", line 9, in <module>
  File "ok/client/cli/ok.py", line 140, in main
  File "ok/client/utils/software_update.py", line 24, in check_version
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1243, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by brianhou** [comment]
Could it be Python 3.5 related?

**Comment by Sumukh** [comment]
Yup - that seems like the cause and would explain why most students in 61A aren't seeing this. There should be a fix using the socket library and a settimeout (or default timeout). I can tackle this in a day or two - but it's up for grabs if anyone wants to solve it.

**Comment by Sumukh** [comment]
It's been reported with python3.4 as well. I suspect it's because of a 1 second timeout + the fact that ok-server has gotten a bit slower due a variety of reasons (smaller memcache)
