### ISSUE TITLE
Error when running python ok

### ISSUE THREAD

**Issue by Some3141** [Cal-CS-61A-Staff/ok-client#19]
There's an error when a student runs "py ok". They get this stacktrace. They can't submit either.

Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ok\__main__.py", line 9, in <module>
  File "ok\client\cli\ok.py", line 122, in main
  File "ok\client\cli\common\assignment.py", line 20, in load_config
  File "ok\client\sources\common\core.py", line 174, in __call__
  File "ok\client\cli\common\assignment.py", line 51, in post_instantiation
  File "ok\client\cli\common\assignment.py", line 86, in _load_tests
  File "ok\client\sources\doctest\__init__.py", line 48, in load
  File "ok\client\sources\common\core.py", line 164, in __call__
  File "ok\client\sources\common\core.py", line 186, in __setattr__
  File "ok\client\sources\common\core.py", line 45, in coerce
TypeError

**Comment by albert12132** [comment]
Do you have a reference for this error?

**Comment by Some3141** [comment]
What do you mean?

**Comment by albert12132** [comment]
Is this from a piazza post? I need more info to replicate the issue.

**Comment by Some3141** [comment]
https://piazza.com/class/i4q8ow8g8bv7oa?cid=111

**Comment by albert12132** [comment]
This post doesn't contain the same stacktrace you mentioned. The error in
the piazza post can be resolved by redownloading ok.

**Comment by Some3141** [comment]
Oh, it was the same person that came to office hours- I guess it was a different error.

But I think to replicate, you just need to use Python 3.4.2 on Gitbash on Windows at worst? I'm not sure which of those variables actually matter.

**Comment by albert12132** [comment]
If you can, ask the student to run OK with the --debug flag, and send that
traceback to me. It'll be more informative.

**Comment by Some3141** [comment]
REDACTED $ py ok --debug
DEBUG | pid 28564 | ok.py:106 | Namespace(authenticate=False, config='ok\\client
\\config.json', debug=True, insecure=False, interactive=False, local=False, lock
=False, question=None, score=False, server='ok-server.appspot.com', submit=False
, tests='tests', timeout=10, unlock=False, verbose=False, version=False)
INFO | pid 28564 | assignment.py:17 | Loaded config from ok\client\config.json
=====================================================================
Assignment: Homework 1
OK, version v1.3.3
=====================================================================

INFO | pid 28564 | assignment.py:63 | Loading tests
INFO | pid 28564 | assignment.py:87 | Loaded hw01.py:hailstone
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ok\__main__.py", line 9, in <module>
  File "ok\client\cli\ok.py", line 122, in main
  File "ok\client\cli\common\assignment.py", line 20, in load_config
  File "ok\client\sources\common\core.py", line 174, in __call__
  File "ok\client\cli\common\assignment.py", line 51, in post_instantiation
  File "ok\client\cli\common\assignment.py", line 86, in _load_tests
  File "ok\client\sources\doctest\__init__.py", line 48, in load
  File "ok\client\sources\common\core.py", line 164, in __call__
  File "ok\client\sources\common\core.py", line 186, in __setattr__
  File "ok\client\sources\common\core.py", line 45, in coerce
TypeError

**Comment by albert12132** [comment]
Managed to find the error. Functions that don't have a docstring have a value of `None` for `func.__doc__`, which is causing TypeErrors. I'll fix this in #23
