### ISSUE TITLE
OSError on cacert.pem

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok-client#236]
From the extra lectures piazza:

```
Traceback (most recent call last):
 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
   "__main__", mod_spec)
 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "/Users/Admin/Desktop/CS 61A/extra02/ok/__main__.py", line 36, in <module>
 File "/Users/Admin/Desktop/CS 61A/extra02/ok/__main__.py", line 17, in patch_requests
OSError: [Errno 0] Error: 'ok/requests/cacert.pem'
```

The student got this after ok auto-updated to the build from GitHub, so it's not a berkeley-cs61a issue.

**Comment by Sumukh** [comment]
Should it be trying to load `ok/requests/cacert.pem`? `requests/cacert.pem` seems to work just fine.

**Comment by Sumukh** [comment]
`requests.__loader__._files` seems to list: 

`'requests/cacert.pem': ('ok/requests/cacert.pem', 0, 344712, 344712, 272152, 47885, 18744, 1765812889), '`  so it might be safer to just call get_data with `requests/cacert.pem`

**Comment by knrafto** [comment]
Seems to have been fixed by https://github.com/Cal-CS-61A-Staff/ok-client/commit/8dc097b293768b29dc4b5a9558618e66687ccca6
