### ISSUE TITLE
Interactive mode does not work when running an individual test case

### ISSUE THREAD

**Issue by jathak** [Cal-CS-61A-Staff/ok-client#330]
```
$ python3 ok --local -q 06 --suite 2 --case 1 -i
=====================================================================
Assignment: Project 2: Yelp Maps
OK, version v1.13.6
=====================================================================

Traceback (most recent call last):
  File "/home/jathak/.linuxbrew/Cellar/python3/3.6.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jathak/.linuxbrew/Cellar/python3/3.6.2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ok/__main__.py", line 46, in <module>
  File "ok/client/cli/ok.py", line 204, in main
  File "ok/client/protocols/grading.py", line 40, in run
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**Comment by khalilsarwari** [comment]
I believe this was resolved by #341
