### ISSUE TITLE
Confusing tracebacks

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#6]
SyntaxErrors (like IndentationErrors) aren't caught and produce an ugly traceback. For example, if hw01.py contains `print 1`, then the traceback below is produced:

```
$ python3 ok
=====================================================================
Assignment: Homework 1
OK, version v1.3.2
=====================================================================

Traceback (most recent call last):
  File "/usr/lib/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "ok/__main__.py", line 9, in <module>
  File "ok/client/cli/ok.py", line 125, in main
  File "ok/client/cli/common/assignment.py", line 21, in load_config
  File "ok/client/sources/common/core.py", line 174, in __call__
  File "ok/client/cli/common/assignment.py", line 52, in post_instantiation
  File "ok/client/cli/common/assignment.py", line 82, in _load_tests
  File "ok/client/sources/doctest/__init__.py", line 23, in load
  File "ok/client/sources/common/importing.py", line 6, in load_module
  File "/usr/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 853, in _load_module
  File "<frozen importlib._bootstrap>", line 980, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "./hw01.py", line 35
    print 1
          ^
SyntaxError: invalid syntax
```

**Comment by albert12132** [comment]
I pushed a hacky fix to make the stacktrace prettier. Can you take a look and test it out?

**Comment by brianhou** [comment]
LGTM.
