### ISSUE TITLE
Running ok-test results in an AttributeError from args.export.

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#85]
```
berkeley-cs61a/src/proj/scheme $ ok-test 
=====================================================================
Assignment: Project 4: A Scheme interpreter
OK, version v1.3.31
=====================================================================

Traceback (most recent call last):
  File "berkeley-cs61a/env/bin/ok-test", line 9, in <module>
    load_entry_point('okpy==v1.3.31', 'console_scripts', 'ok-test')()
  File "berkeley-cs61a/env/lib/python3.3/site-packages/client/cli/test.py", line 53, in main
    grading.protocol(args, assign).run(msgs)
  File "berkeley-cs61a/env/lib/python3.3/site-packages/client/protocols/grading.py", line 31, in run
    if self.args.score or self.args.export:
AttributeError: 'Namespace' object has no attribute 'export'
```

**Comment by brianhou** [comment]
The same thing is now happening with `args.restore`. It might be a good idea to have just one interface that `ok.py` and `test.py` share, so we don't have to remember to add arguments to both files.
