### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok-client#90]
I'm not sure why this error would occur. @soumyabasu or @Sumukh , any ideas? @jeffreylu017 has more information.

```
Exception happened during processing of request from ('127.0.0.1', 57055)

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1182, in do_open

    h.request(req.get_method(), req.selector, req.data, headers)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1088, in request

    self._send_request(method, url, body, headers)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1126, in _send_request

    self.endheaders(body)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1084, in endheaders

    self._send_output(message_body)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 922, in _send_output

    self.send(msg)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 857, in send

    self.connect()

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1231, in connect

    server_hostname=server_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 365, in wrap_socket

    _context=self)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 583, in __init__

    self.do_handshake()

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 810, in do_handshake

    self._sslobj.do_handshake()

ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock

    self.process_request(request, client_address)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socketserver.py", line 331, in process_request

    self.finish_request(request, client_address)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socketserver.py", line 344, in finish_request

    self.RequestHandlerClass(request, client_address, self)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socketserver.py", line 673, in __init__

    self.handle()

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/server.py", line 398, in handle

    self.handle_one_request()

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/server.py", line 386, in handle_one_request

    method()

  File "ok/client/utils/auth.py", line 118, in do_GET

    access_token, refresh_token, expires_in = _make_code_post(code)

  File "ok/client/utils/auth.py", line 48, in _make_code_post

    client.request_token(code=code, **params)

  File "ok/client/utils/sanction/__init__.py", line 131, in request_token

    'utf-8'))

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen

    return opener.open(url, data, timeout)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 463, in open

    response = self._open(req, data)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 481, in _open

    '_open', req)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain

    result = func(*args)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1225, in https_open

    context=self._context, check_hostname=self._check_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1184, in do_open

    raise URLError(err)

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

----------------------------------------

Checking for software updates...

Network error when checking for updates.

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main

    "__main__", mod_spec)

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "ok/__main__.py", line 9, in <module>

  File "ok/client/cli/ok.py", line 108, in main

  File "ok/client/protocols/backup.py", line 31, in run

  File "ok/client/utils/auth.py", line 133, in authenticate

  File "ok/client/utils/auth.py", line 70, in update_storage

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by Sumukh** [comment]
We've seen this before on some computers. (Macbook Airs from the UCB library if you want to replicate)
It might have to do with the trusted certs on the machine. 
Suggested fixes: http://bugs.python.org/issue23476

A similiar discussion should be in your email from last semester if you search for ssl (sent by me)

**Comment by papajohn** [comment]
I think it's possible that upgrading Python will address this issue.

**Comment by albert12132** [comment]
It seems like the student was using Python3.5.0b2. Once she downgraded to a stable version of Python3.4, the issue went away.

**Comment by jeffreylu017** [comment]
That was a different student.  My student still hasn't resolved this issue.  Haven't been able to meet up with her though, so I'm not sure how to debug it through email.

**Comment by soumyabasu** [comment]
This was resolved when the student moved from 32 bit Python to 64 bit Python.

**Comment by jeffreylu017** [comment]
Soumya figured it out.  Student was using 32-bit of version when the OS was 64-bit.  This might apply to the other problems as well.
